name: nest-ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # - name: Setup Node | ${{ matrix.node }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node }}
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Test 
        run: pnpm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ue-east-2
          role-to-assume: arn:aws-cn:iam::123456789100:role/my-github-actions-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: lucasmachado13/nest-ci:${{ steps.generate_tag.outputs.sha }},lucasmachado13/nest-ci:latest

      # - name: Build docker image
      #   run: docker build -t lucasmachado13/nest-ci:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push image
      #   run: docker push lucasmachado13/nest-ci:${{ steps.generate_tag.outputs.sha }}
